{{- if and (.Values.hiera.eyaml.public_key) (not .Values.r10k.hiera.viaSsh.credentials.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name:  {{ include "puppetserver.hiera.publicSecret" . }}
  labels:
    {{- include "puppetserver.hiera.labels" . | nindent 4 }}
data:
  public_key.pkcs7.pem: |-
    {{ .Values.hiera.eyaml.public_key | nindent 4 | b64enc }}
{{- end }}
